### ISSUE TITLE
改行がそのままのこる

### ISSUE THREAD

**Issue by tosh13** [nnh/gd-slicer#12]
https://docs.google.com/document/d/1W_0JLfOpYFxhIPgunP73QraOj86GY30pzoeIwnUe9Fk/edit#heading=h.bn4swwocy5dx

**Comment by katsusuke** [comment]
@tosh13 
https://docs.google.com/document/d/11DptOhCJf3gdLW2A69KMwUQxwdTHLpn4AGsQWTkPAa8
にデプロイいたしました。再度ご確認お願いいたします
